add: skipボタンを押すことで掃除当番をskipできるようにした
esminc/Miffy pull request #29
Opened 2020-09-01 08:25 UTC by RyuyaMaeda

@uesaka-seiya 
skipボタンを押すことで掃除当番をskipできるようにしました
レビューの方よろしくお願いします

2020-09-10 08:24 UTC, uesaka-seiya requested changes
@RyuyaMaeda 
レビューしました。ご確認お願いします。

2020-09-10 08:24 UTC, uesaka-seiya commented on src/main/resources/templates/asf4members.html
> +    <input type="submit" formaction="/skip" value="今日は掃除当番できない"/>
`今日は掃除当番できない`ボタンは使用頻度が高いので`変更`ボタンより上（右？）のほうが良いと思います

2020-09-25 15:02 UTC, RyuyaMaeda commented on src/main/resources/templates/asf4members.html
> +    <input type="submit" formaction="/skip" value="今日は掃除当番できない"/>
レビューありがとうございます。
今日は掃除できないボタンを上（左？）に移動しました。(masterブランチを取り込んでコンフリクト解消しただけ)
ご確認よろしくお願いします。

2020-09-28 00:03 UTC, uesaka-seiya commented
🆗 です！マージしますね

2020-09-28 00:03 UTC, merged

2020-09-28 00:05 UTC, uesaka-seiya reviewed
おk