Controllerクラスのリファクタリングをした
esminc/Miffy pull request #47
Opened 2020-12-24 23:26 UTC by RyuyaMaeda

### やったこと
* modelattributeの書式を統一した
* Asf4MemberControllerクラスが冗長だったため、削除した
* 不要な文を削除した
* documentation commentを編集した
* メソッド名、ファイル名を修正した
### やらないこと
* idobataIDを主キーにして被りをなくす(別issueで対応)

2021-01-08 09:28 UTC, uesaka-seiya requested changes
確認しました（1箇所だけ修正お願いします）
マージしてからバグ修正したいなーと思いつつバグの原因が複数ありそうでまだ調査中です

2021-01-08 09:28 UTC, uesaka-seiya commented on src/main/java/jp/co/esm/miffy/component/HookComponent.java
> +     private static final String URL = "https://idobata.io/hook/custom/36145675-8b2f-4b78-bf2b-9e06577e0434";//PR用;
マージする前に本番用に戻さなきゃですね

2021-02-25 23:46 UTC, RyuyaMaeda commented on src/main/java/jp/co/esm/miffy/component/HookComponent.java
> +     private static final String URL = "https://idobata.io/hook/custom/36145675-8b2f-4b78-bf2b-9e06577e0434";//PR用;
本番用に戻しました
ご確認よろしくお願いします

2021-02-25 23:57 UTC, uesaka-seiya commented on src/main/java/jp/co/esm/miffy/component/HookComponent.java
> +     private static final String URL = "https://idobata.io/hook/custom/36145675-8b2f-4b78-bf2b-9e06577e0434";//PR用;
LGTMです

2021-02-25 23:57 UTC, uesaka-seiya approved these changes
LGTMです

2021-03-30 01:14 UTC, merged